var mongoose = require('mongoose');

module.exports = mongoose.model('User', {
	userid : {type : String, default: ''},
	password : {type : String, default: ''},
	employeeid : {type : String, default: ''},
	title : {type : String, default: ''},	
	roleid : {type : Number, default: 0},
	roleText : {type : String, default: ''},	
	teamid : {type : Number, default: 0},
	teamText : {type : String, default: ''},		
	firstname : {type : String, default: ''},	
	middlename : {type : String, default: ''},	
	lastname : {type : String, default: ''},	
	billingtypeid : {type : Number, default: 0},
	billingtypeText : {type : String, default: ''},
	teamleadid : {type : String, default: 0},
	teamleadText : {type : String, default: ''},	
	locid : {type : Number, default: 0},
	locText : {type : String, default: ''},		
	desigid : {type : Number, default: 0},
	desigText : {type : String, default: ''},
    isu : {type : String, default: ''},
	usertypeid : {type : Number, default: 0},	
	usertypeText : {type : String, default: ''},
	companyid : {type : Number, default: 0},	
	companyText : {type : String, default: ''},
	mobileno : {type : String, default: ''},
	deskphno : {type : String, default: ''},	
	geoid : {type : Number, default: 0},
	geoText : {type : String, default: ''},

	isProjectUser : {type : Boolean, default: false},
	isTimeSheetUser : {type : Boolean, default: false},
	isProjectReportUser : {type : Boolean, default: false},
	isTimeSheetReportUser : {type : Boolean, default: false},
	isTimeSheetUserAllocation : {type : Boolean, default: false},
		
});